"""empty message

Revision ID: 46988755f2cf
Revises: 490ee034c18f
Create Date: 2023-12-13 12:50:22.608320

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '46988755f2cf'
down_revision = '490ee034c18f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_contact_requests_timestamp')
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.create_index('ix_contact_requests_timestamp', ['timestamp'], unique=False)

    # ### end Alembic commands ###
