"""empty message

Revision ID: 490ee034c18f
Revises: 21e52cb02dc2
Create Date: 2023-12-13 12:17:01.962119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '490ee034c18f'
down_revision = '21e52cb02dc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.String(length=500), nullable=True))
        batch_op.drop_column('details')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.drop_column('message')

    # ### end Alembic commands ###
