"""empty message

Revision ID: 753a0e157737
Revises: 46988755f2cf
Create Date: 2023-12-13 17:59:10.449381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '753a0e157737'
down_revision = '46988755f2cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checkout_request_id', sa.String(length=100), nullable=False),
    sa.Column('employer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['employers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checkout_request_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_mapping')
    # ### end Alembic commands ###
